name: "Terraform CI"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Validate and Plan"
    runs-on: ubuntu-latest

    # Specify container image
    container:
      image: hashicorp/terraform:latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        run: |
          terraform -v
          terraform init -input=false ./terraform/

      - name: Terraform Validate
        run: terraform validate ./terraform/

      - name: Terraform Plan
        run: terraform plan -input=false ./terraform/
