name: "Terraform CI"

on:
  push:
    branches:
      - main

env:
  TERRAFORM_DIR: './terraform' # Define an environment variable for the Terraform directory

jobs:
  terraform:
    name: "Terraform Validate and Plan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        run: terraform -chdir=${{ env.TERRAFORM_DIR }} init -input=false

      - name: Terraform Validate
        run: terraform -chdir=${{ env.TERRAFORM_DIR }} validate

      - name: Terraform Plan
        run: terraform -chdir=${{ env.TERRAFORM_DIR }} plan -input=false
